language: python
python:
    - 3.7
    - 3.8
    - 3.9

# command to install dependencies
install:
    - pip3 install --upgrade six
    - make install

# command to run tests
script:
    - make test

notifications:
  email:
    on_success: change
    on_failure: change
